name: Upload Python Package
on:
  push:
    tags:
      - "*.*.*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "PYTHON_VERSION"

      - name: Install poetry
        run: |
          pip install poetry

      - name: Build and publish
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          poetry publish --build --username ${PYPI_USERNAME} --password ${PYPI_PASSWORD}
