name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "bugfix"
      - "bug"
  - title: "🧪 Test"
    labels:
      - "test"
  - title: "📘 Documentation"
    labels:
      - "documentation"
      - "document"
  - title: "⚙️ CI/CD"
    labels:
      - "cicd"
  - title: "🔗 Dependency"
    labels:
      - "dependency"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "refactor"
change-template: "- $TITLE (#$NUMBER)"
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
autolabeler:
  - label: "feature"
    branch:
      - '/feat\/.+/'
  - label: "bugfix"
    branch:
      - '/fix\/.+/'
  - label: "cicd"
    branch:
      - '/cicd\/.+/'
    files:
      - ".github/**/*"
      - ".pre-commit-config.yml"
      - "codedcov.yml"
  - label: "documentation"
    files:
      - "*.md"
      - "doc/**/*"
    branch:
      - '/doc\/.+/'
  - label: "test"
    branch:
      - '/test\/.+/'
  - label: "chore"
    branch:
      - '/chore\/.+/'
  - label: "refactor"
    branch:
      - '/refactor\/.+/'
  - label: "version"
    branch:
      - '/version\/.+/'
  - label: "code"
    files:
      - "pypj/**/*"
  - label: "dependency"
    files:
      - "poetry.lock"
  - label: "pyproject"
    files:
      - "pyproject.toml"
  - label: "python"
    files:
      - "python-version"
template: |
  ## Changes

  $CHANGES
