default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/csachs/pyproject-flake8
    rev: v0.0.1a2.post1
    hooks:
      - id: pyproject-flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.9.2
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: make unittest
        language: system
