name: Mark stale pull requests

on:
  schedule:
  - cron: "0 0 * * *"
permissions:
  pull-requests: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: 'This PR is stale because it has been open for 10 days with no activity.'
        stale-pr-label: 'stale'
        days-before-stale: 10
        days-before-close: -1
